server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TheCodeYinChao/spring-cloud-repo.git
          username:
          password: