server:
  port: 8010

api.user.url: http://localhost:8000/


eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
        defaultZone: http://user:123456@peer1:8761/eureka
  instance:
    prefer-ip-address: true